# -*- coding: utf-8 -*-
"""Medicare_Medication.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10XPVIg-c2qknuoP9tVmRi-p3G6hk6_s4

###Context and Dictionary

The insurance company Alpha Green (Not a real company) wants to make changes for their formulary for select Medicare Advantage policies and supplements in 2024. They have asked me to look over the formulary data for the previous years to get a gist for the territory, and create a list of medications that can be reliable removed from a formulary. My goal is to answer the following:

- **Which medications have few beneficiaries but are expensive to cover?**

**Data Dictionary:**

https://data.cms.gov/resources/medicare-part-b-spending-by-drug-data-dictionary

**Drug Info:**

HCPCS Code: This just means the code for the medication.

HCPCS Description:: This is the the form it comes in (pill, injection) and what it does.

Brnd_Name: The brand name of the medication.

Gnrc_Name: The generic name of the medication.  

---

**Facts (2019)**:

HCPCS_Cd: This just means the code for the medication

Tot_Spndng_2019: The total amount spent for the medication during 2019.

Tot_Dsg_Units_2019: The total number of dosage units of the specified medication for 2019.
 - Note: A dosage unit is the measurement of whatever constitutes one single dose of the specified medication. Maybe for vyvanse it's one pill, maybe for hydrochlorothiazide it's 2 pills depending on the beneficiary.

Tot_Benes_2019: This is the total number of beneficiaries using this medication in 2019.

Avg_Spndng_Per_Dsg_Unt_2019: This shows the average cost of 1 dosage unit of the specified medication.

Avg_Spndng_Per_Clm_2019: This shows the average spending per claim of the specified medication.

Avg_Spndng_Per_Bene_2019: This shows the average spending per beneficary of the specified medication.

Outlier_Flag_2019: This basically flags outliers. If something about this medication looked unusual in 2019, then it is flagged as an outlier.

**Repeat this table for 2020-2023**

---
**Miscellaneous**:

Avg_DY23_ASP_Price: This is the 2023 average sales price per unit of medication.

Chg_Avg_Spndng_Per_Dsg_Unt_22_23: This is the difference between average spending per dosage between 2022 and 2023.

CAGR_Avg_Spnd_Per_Dsg_Unt_19_23: This is the difference between average spending per dosage between 2019 and 2023.

###Imports and Information:

Here, I will import the necessary libraries to preprocess the data and do a quick overview.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import json
import warnings
warnings.filterwarnings("ignore")

file = '/content/drive/MyDrive/Datasets/DSD_PTB_RY25_P06_V10_DYT23_HCPCS- 250430.csv'
df = pd.read_csv(file)
df.head()

df.info()

print(f'There are {df.duplicated().sum()} duplicates')

"""**Observations:**

Missing Data:

- For the categorical values, there isn't much missing data. The only one with missing data is Gnrc_Name, which just implies a medication doesn't have a generic. These can be left empty or replaced with 'None.'

- As for the numeric values, they are either column calculations or raw numbers taken from real world formulary statistics. This means that if something is missing it is unlikely to mean '0 instances' unless it's a very specialized medication. It more likely means there's actual missing data. Also, there is too much missing data per column to impute a value, so I'll need to leave them blank and account for null values in future code.

- Looking at the raw spreadsheet, there are also several scenarios in which a medication or multiple medications will have null data for one year, but then have populated data for the next year. The year with the fewest missing values by far is 2023.

Duplicates:

- There are no true duplicate values. Hooray~. I'll still keep an eye out as I work just in case.

Data Structure:

- This data needs to be melted. What I mean is, we have columns with the same data for different years. Since this is going into Power BI, I want to be able to aggregate things by year and see timeline shifts, so It's probably best if we melt them down.

###Melting the Data

Here, I will turn the data from a wide set into a long set, and I will create a 'date' column to mark the new structure.
"""

df[['Avg_Spndng_Per_Dsg_Unt_2022', 'Avg_Spndng_Per_Dsg_Unt_2023', 'Chg_Avg_Spndng_Per_Dsg_Unt_22_23']].head()

df_tot_spndng = df.melt(
    id_vars = ['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name'],
    value_vars = ['Tot_Spndng_2019','Tot_Spndng_2020','Tot_Spndng_2021','Tot_Spndng_2022','Tot_Spndng_2023'],
    var_name = 'year',
    value_name = 'Tot_Spndng'
)

df_tot_spndng['year'] = df_tot_spndng['year'].str.extract('(\d{4})').astype(int)
df_tot_spndng.head()

df_tot_spndng.duplicated(subset=['HCPCS_Cd', 'year']).sum()

"""This code takes the specified items (value_vars) and combines them into one column (value_name) "Tot_spndng." Then it partitions them by the 'year' column to ensure it's organized correctly. I also checked for duplicates to make sure nothing went wrong, and nothing did. I'll repeat this process for the other items as well."""

df_tot_dsg_units = df.melt(
    id_vars=['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name'],
    value_vars=['Tot_Dsg_Unts_2019','Tot_Dsg_Unts_2020','Tot_Dsg_Unts_2021','Tot_Dsg_Unts_2022','Tot_Dsg_Unts_2023'],
    var_name='year',
    value_name='Tot_Dsg_Unts'
)

df_tot_dsg_units['year'] = df_tot_dsg_units['year'].str.extract('(\d{4})').astype(int)
df_tot_dsg_units.head()

df_tot_benes = df.melt(
    id_vars=['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name'],
    value_vars=['Tot_Benes_2019','Tot_Benes_2020','Tot_Benes_2021','Tot_Benes_2022','Tot_Benes_2023'],
    var_name='year',
    value_name='Tot_Benes'
)

df_tot_benes['year'] = df_tot_benes['year'].str.extract('(\d{4})').astype(int)
df_tot_benes.head()

df_avg_spndng_per_dsg_unt = df.melt(
    id_vars=['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name'],
    value_vars=['Avg_Spndng_Per_Dsg_Unt_2019',
                'Avg_Spndng_Per_Dsg_Unt_2020',
                'Avg_Spndng_Per_Dsg_Unt_2021',
                'Avg_Spndng_Per_Dsg_Unt_2022',
                'Avg_Spndng_Per_Dsg_Unt_2023'],
    var_name='year',
    value_name='Avg_Spndng_Per_Dsg_Unt'
)

df_avg_spndng_per_dsg_unt['year'] = df_avg_spndng_per_dsg_unt['year'].str.extract('(\d{4})').astype(int)
df_avg_spndng_per_dsg_unt.head()

df_avg_spndng_per_clm = df.melt(
    id_vars=['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name'],
    value_vars=['Avg_Spndng_Per_Clm_2019',
                'Avg_Spndng_Per_Clm_2020',
                'Avg_Spndng_Per_Clm_2021',
                'Avg_Spndng_Per_Clm_2022',
                'Avg_Spndng_Per_Clm_2023'],
    var_name='year',
    value_name='Avg_Spndng_Per_Clm'
)

df_avg_spndng_per_clm['year'] = df_avg_spndng_per_clm['year'].str.extract('(\d{4})').astype(int)
df_avg_spndng_per_clm.head()

df_avg_spndng_per_bene = df.melt(
    id_vars=['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name'],
    value_vars=['Avg_Spndng_Per_Bene_2019',
                'Avg_Spndng_Per_Bene_2020',
                'Avg_Spndng_Per_Bene_2021',
                'Avg_Spndng_Per_Bene_2022',
                'Avg_Spndng_Per_Bene_2023'],
    var_name='year',
    value_name='Avg_Spndng_Per_Bene'
)

df_avg_spndng_per_bene['year'] = df_avg_spndng_per_bene['year'].str.extract('(\d{4})').astype(int)
df_avg_spndng_per_bene.head()

df_tot_clms = df.melt(
    id_vars=['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name'],
    value_vars=['Tot_Clms_2019',
                'Tot_Clms_2020',
                'Tot_Clms_2021',
                'Tot_Clms_2022',
                'Tot_Clms_2023'],
    var_name='year',
    value_name='Tot_Clms'
)

df_tot_clms['year'] = df_tot_clms['year'].str.extract('(\d{4})').astype(int)
df_tot_clms.head()

df_outlier_flag = df.melt(
    id_vars=['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name'],
    value_vars=['Outlier_Flag_2019',
                'Outlier_Flag_2020',
                'Outlier_Flag_2021',
                'Outlier_Flag_2022',
                'Outlier_Flag_2023'],
    var_name='year',
    value_name='Outlier_Flag'
)

df_outlier_flag['year'] = df_outlier_flag['year'].str.extract('(\d{4})').astype(int)
df_outlier_flag.head()

"""All the tables have been melted based on date. Now I just need to join them into one csv file.

###Merging the Data

In order to melt the data, I had to slice it up into parts. In this section, I will combine it into 1 csv file.
"""

master_df = df_tot_spndng.merge(
    df_tot_dsg_units,
    on = ['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name', 'year'],
    how='inner'
)

"""This code just merges the table by these identifiers: ['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name', 'year']. I'll repeat the process for each table."""

master_df = master_df.merge(
    df_tot_benes,
    on = ['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name', 'year'],
    how='inner'
)

master_df = master_df.merge(
    df_avg_spndng_per_dsg_unt,
    on = ['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name', 'year'],
    how='inner'
)

master_df = master_df.merge(
    df_avg_spndng_per_clm,
    on = ['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name', 'year'],
    how='inner'
)

master_df = master_df.merge(
    df_avg_spndng_per_bene,
    on = ['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name', 'year'],
    how='inner'
)

master_df = master_df.merge(
    df_tot_clms,
    on = ['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name', 'year'],
    how='inner'
)

master_df = master_df.merge(
    df_outlier_flag,
    on = ['HCPCS_Cd', 'HCPCS_Desc', 'Brnd_Name', 'Gnrc_Name', 'year'],
    how='inner'
)

master_df.head()

master_df.info()

"""###Outliers and Duplicates

Now that we have one cohesive data table, I want to make sure it's tidy. I'll start by checking for outliers.
"""

numcols = master_df.select_dtypes(include = ['float64'])
for i in numcols:
  plt.figure(figsize = (5,5))
  sns.boxplot(master_df, y = i, palette = 'bone')
  plt.show()

"""**Observation:**

It looks like we have some consistent skew in all numeric columns. I'll check them individually to ensure the outliers aren't erroneous.
"""

plt.figure(figsize = (5,5))
sns.boxplot(master_df, y = 'Tot_Spndng', palette = 'bone')
plt.show()

outliers1 = master_df[master_df['Tot_Spndng'] > 2e9][['Tot_Spndng', 'Outlier_Flag', 'Brnd_Name']]
outliers1

"""**Observation:**

- There are only 4 medications in the outliers I cut for total spending: Keytruda, Eylea, Prolia* and Darzalex Faspro. All of these make sense, as they are all highly expensive specialized medications. They are most likely not erroneous.
"""

plt.figure(figsize = (5,5))
sns.boxplot(master_df, y = 'Tot_Dsg_Unts', palette = 'bone')
plt.show()

outliers2 = master_df[master_df['Tot_Dsg_Unts'] > 4e8][['Tot_Dsg_Unts', 'Outlier_Flag', 'Brnd_Name', 'year']]
outliers2

"""**Observation:**

- The only drug exceeding my marked outlier is Yupelri. Yupelri is a somewhat common drug used to treat lung disease. It's a once-a-day pill that's covered by most insurances, lending credence to it's high number. Also, it's high number is consistent across all 4/5 years, and it increases in use in chronological order, lending it further credibility. It's formatted correctly, it makes sense, I don't believe this is an error, and I will leave it in the data.
"""

plt.figure(figsize = (5,5))
sns.boxplot(master_df, y = 'Tot_Benes', palette = 'bone')
plt.show()

outliers3 = master_df[master_df['Tot_Benes'] > 3e6][['Tot_Benes', 'Outlier_Flag', 'Brnd_Name', 'year']]
outliers3

"""**Observations:**

- The 4 items caught above my outlier cap are all common vaccines for the flu and covid 19, so it makes sense that they would have a lot of beneficiaries. HOWEVER, vaccines might not be the best indicator of what should and shouldn't go on a forumuarly since they're near obligatory with most policies, so factoring them into the investigation might not be very effective. They may be cut depending on the questions to be answered.
"""

plt.figure(figsize = (5,5))
sns.boxplot(master_df, y = 'Avg_Spndng_Per_Dsg_Unt', palette = 'bone')
plt.show()

outliers3 = master_df[master_df['Avg_Spndng_Per_Dsg_Unt'] > 300000][['Avg_Spndng_Per_Dsg_Unt', 'Outlier_Flag', 'Brnd_Name', 'year']]
outliers3

"""**Observations:**

- The 5 medications here are very expensive. They're usually used to treat cancer or lymphoma and can cost hundreds of thousands of dollars out of pocket without insurance. It makes sense that they would have a high price, but it should be noted that Yescarta, Kymriah, Breyanzi and Tecartus were flagged as outliers by the dataset in select years. If they appear in SQL query output, they should be double checked, but they don't need to be removed from the dataset itself.
"""

plt.figure(figsize = (5,5))
sns.boxplot(master_df, y = 'Avg_Spndng_Per_Clm', palette = 'bone')
plt.show()

outliers4 = master_df[master_df['Avg_Spndng_Per_Clm'] > 200000][['Avg_Spndng_Per_Clm', 'Outlier_Flag', 'Brnd_Name', 'year']]
outliers4

"""**Observations:**

- These are the same outliers as in Average Spending Per Dosage Unit. Therefore the same things explained there apply here.
"""

plt.figure(figsize = (5,5))
sns.boxplot(master_df, y = 'Avg_Spndng_Per_Bene', palette = 'bone')
plt.show()

outliers4 = master_df[master_df['Avg_Spndng_Per_Bene'] > 600000][['Avg_Spndng_Per_Bene', 'Outlier_Flag', 'Brnd_Name', 'year']].sort_values(by = 'Brnd_Name')
outliers4

"""**Observations:**

- Just like with the other columns, these medications are expensive, but they do exist, and likely aren't erroneous.

The last thing I want to do is check for any **true** duplicates. If a row is completely identical to another row, then it's likely erroneous.
"""

master_df.duplicated().sum()

subset = ['HCPCS_Cd', 'year']
master_df.duplicated(subset = subset).sum()

"""There are no true duplicates or drugs with both the same date and ID. This means that there were likely no issues during the melting process.

###Final Check

The data has been preprocessed and the outliers and missing values have been properly verified and managed. Next I will convert it into a csv and import it into MySQL.
"""

master_df.info()

master_df['HCPCS_Cd'] = master_df['HCPCS_Cd'] + '_' + master_df['year'].astype(str)
master_df['HCPCS_Cd']

master_df['HCPCS_Cd'].nunique()

columns = ['HCPCS_Cd', 'Brnd_Name', 'Gnrc_Name', 'year', 'Tot_Clms']

test = master_df[master_df['Brnd_Name'] == 'Imogam Rabies-HT']
test[columns].head(5)

master_df.to_csv('medicare_drug_master.csv', index = False, na_rep='\\N')

"""This concludes the python data preprocessing. Please return to github and reference the README file to see the rest of the project."""
